### ISSUE TITLE
Wrong class used for PaymentCostInterface::setExtensionAttributes

### ISSUE THREAD

**Issue by vincenthornikx** [dealer4dealer/magento2-restapi#16]
In the current version (2.0.0) the methods \Dealer4dealer\Xcore\Api\Data\PaymentCostInterface::getExtensionAttributes() and \Dealer4dealer\Xcore\Api\Data\PaymentCostInterface::setExtensionAttributes() use the wrong return and argument type respectively.

This should not be ```\Dealer4dealer\Xcore\Api\Data\PaymentCostInterface```, it should be ```\Dealer4dealer\Xcore\Api\Data\PaymentCostExtensionInterface```.

With the current version setup:di:compile cannot be run succesfully.

Regards,
Vincent

**Comment by HenriNijborg** [comment]
Issue should be resolved in 2.0.1
