### ISSUE TITLE
Dependency on Magento_Tax not listed in module.xml

### ISSUE THREAD

**Issue by Tjitse-E** [dealer4dealer/magento2-restapi#21]
This module has a dependency on Magento_Tax (https://github.com/dealer4dealer/magento2-restapi/blob/9f2cc22f6929a6508844e30cbdfc0784a5971864/Setup/UpgradeData.php#L18) but this is not listed in the module.xml, causing errors on Magento 2 setup with the module installed.

**Comment by HenriNijborg** [comment]
Resolved in 2.1.4
