### ISSUE TITLE
Cannot update D4D module via composer to 2.2.4 in M2.4

### ISSUE THREAD

**Issue by onepack** [dealer4dealer/magento2-restapi#29]
Magento 2.4 has sales   "version": "103.0.0"
 
 Problem 1
    - Installation request for dealer4dealer/xcore-magento2 2.2.4 -> satisfiable by dealer4dealer/xcore-magento2[2.2.4].
    - Conclusion: remove laminas/laminas-code 3.4.1
    - Conclusion: don't install laminas/laminas-code 3.4.1
    - dealer4dealer/xcore-magento2 2.2.4 requires magento/module-sales ^102.0 -> satisfiable by magento/module-sales[102.0.5-p2, 102.0.4-p2, 102.0.5, 102.0.3-p1, 102.0.4, 102.0.3, 102.0.2, 102.0.1, 102.0.0].
    - magento/module-sales 102.0.5-p2 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.5-p2, 102.0.4-p2, 102.0.5, 102.0.3-p1, 102.0.4, 102.0.2-p2, 102.0.3, 102.0.2, 102.0.1, 102.0.0].
    - magento/module-sales 102.0.4-p2 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.5-p2, 102.0.4-p2, 102.0.5, 102.0.3-p1, 102.0.4, 102.0.2-p2, 102.0.3, 102.0.2, 102.0.1, 102.0.0].
    - magento/module-sales 102.0.5 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.5-p2, 102.0.4-p2, 102.0.5, 102.0.3-p1, 102.0.4, 102.0.2-p2, 102.0.3, 102.0.2, 102.0.1, 102.0.0].
    - magento/module-sales 102.0.3-p1 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.5-p2, 102.0.4-p2, 102.0.5, 102.0.3-p1, 102.0.4, 102.0.2-p2, 102.0.3, 102.0.2, 102.0.1, 102.0.0].
    - magento/module-sales 102.0.4 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.5-p2, 102.0.4-p2, 102.0.5, 102.0.3-p1, 102.0.4, 102.0.2-p2, 102.0.3, 102.0.2, 102.0.1, 102.0.0].
    - magento/module-sales 102.0.3 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.5-p2, 102.0.4-p2, 102.0.5, 102.0.3-p1, 102.0.4, 102.0.2-p2, 102.0.3, 102.0.2, 102.0.1, 102.0.0].
    - magento/module-sales 102.0.2 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.5-p2, 102.0.4-p2, 102.0.5, 102.0.3-p1, 102.0.4, 102.0.2-p2, 102.0.3, 102.0.2, 102.0.1, 102.0.0].
    - magento/module-sales 102.0.1 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.5-p2, 102.0.4-p2, 102.0.5, 102.0.3-p1, 102.0.4, 102.0.2-p2, 102.0.3, 102.0.2, 102.0.1, 102.0.0].
    - magento/module-sales 102.0.0 requires magento/framework 102.0.* -> satisfiable by magento/framework[102.0.5-p2, 102.0.4-p2, 102.0.5, 102.0.3-p1, 102.0.4, 102.0.2-p2, 102.0.3, 102.0.2, 102.0.1, 102.0.0].
    - magento/framework 102.0.5-p2 requires laminas/laminas-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.4-p2 requires zendframework/zend-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2], zendframework/zend-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.5 requires laminas/laminas-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.3-p1 requires zendframework/zend-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2], zendframework/zend-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.4 requires zendframework/zend-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2], zendframework/zend-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.2-p2 requires zendframework/zend-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2], zendframework/zend-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.3 requires zendframework/zend-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2], zendframework/zend-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.2 requires zendframework/zend-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2], zendframework/zend-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.1 requires zendframework/zend-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2], zendframework/zend-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.0 requires zendframework/zend-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2], zendframework/zend-code[3.3.0, 3.3.1, 3.3.2].
    - Can only install one of: laminas/laminas-code[3.3.0, 3.4.1].
    - Can only install one of: laminas/laminas-code[3.3.1, 3.4.1].
    - Can only install one of: laminas/laminas-code[3.3.2, 3.4.1].
    - don't install zendframework/zend-code 3.3.0|don't install laminas/laminas-code 3.4.1
    - don't install zendframework/zend-code 3.3.1|don't install laminas/laminas-code 3.4.1
    - don't install zendframework/zend-code 3.3.2|don't install laminas/laminas-code 3.4.1
    - Installation request for laminas/laminas-code (locked at 3.4.1) -> satisfiable by laminas/laminas-code[3.4.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by JelleGe** [comment]
Same issue here.

**Comment by HenriNijborg** [comment]
Apart from the issue above, Magento 2.4 isn't supported yet when using the xCore. It requires a different authentication method for the API using an integration token because of the mandatory 2FA. The issue for this and support for Magento 2.4 overall is on our current sprint which means it will be developed, tested and released within the next three weeks. For more information please contact our servicedesk at servicedesk@dealer4dealer.nl.

**Comment by onepack** [comment]
Hi Henri,

A bit more pro-active approach would be really appreciated as 2.4 didn't just happen overnight.

Nevertheless thanks for the update!

**Comment by HenriNijborg** [comment]
The extension is updated so it can be installed with Magento 2.4.* but the functionality for the authentication, using the integration token from the xCore, is currently in the test fase. When this is released I will update this issue. We expect to release it in the current or next week.

**Comment by HenriNijborg** [comment]
I just released the support for using the Magento integration token instead of Basic Auth within the xCore. It requires extension version 2.4.1 or higher. When updating to Magento 2.4 it requires the xCore app to reauthenticate using the token from the Magento 2 integration. For any questions or support, please send it to servicedesk@dealer4dealer.nl.
