### ISSUE TITLE
Tierprice updates raise error log notification

### ISSUE THREAD

**Issue by rofokken** [dealer4dealer/magento2-restapi#51]
See:

https://github.com/xcoreplatform/magento2-restapi/blob/43feffdda12382852154b85c8a18fb424ed9db3b/Model/Product/Price/TierPriceStorage.php#L61

Plz remove this log line.

We have many false errors raised in our monitoring.

**Comment by HenriNijborg** [comment]
Solved in release https://github.com/xcoreplatform/magento2-restapi/releases/tag/2.11.2
